### ISSUE TITLE
Split project into multiple repositories

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#1]
In due course we will need separate repositories for:
- [x] The new Django version of the website
- [x] The experiment runner task-queue (currently part of the [fcweb](https://github.com/ModellingWebLab/fcweb) repository
- [x] The backend cardiac simulation code (currently on the [Chaste Trac server](https://chaste.cs.ox.ac.uk/trac/browser/chaste/projects/FunctionalCuration))
- [x] The replacement for [pycml](https://chaste.cs.ox.ac.uk/trac/browser/git_repo/python/pycml) (which should probably include the [CompactSyntaxParser](https://chaste.cs.ox.ac.uk/trac/browser/chaste/projects/FunctionalCuration/src/proto/parsing/CompactSyntaxParser.py))

Others may be added in the future.

**Comment by MichaelClerx** [comment]
How are we naming the individual python modules? `weblab.x`, `weblab.y`, etc.? Or standalone names like `web_lab_related_x`, `web_lab_related_y` ?

**Comment by jonc125** [comment]
Standalone names, so each can be pip-installable separately. They may or may not have `web_lab` in the name; the task queue & Django site probably should, the backend experiment running & fitting code probably not, since they could be used independently.

**Comment by jonc125** [comment]
Trac ticket on comparing the C++ & Python backends: https://chaste.cs.ox.ac.uk/trac/ticket/2643

**Comment by jonc125** [comment]
What should we call the new pycml? (Which will be used for the repo & Python package name.) Stick with pycml? Or come up with something new?

**Comment by MichaelClerx** [comment]
No idea!

On the one hand, we want our new modules (`functional-curation-with-solver`, `cellml-reader-with-exports`, `generic-web-lab-front-end` and `cardiac-web-lab-front-end`*) to be independent, so you can download, use and develop them separately.

But on the other hand, we want short names with some kind of common theme so that it's obvious the projects are linked...

(*We also don't want them to be this awful)

**Comment by MichaelClerx** [comment]
...but maybe if the libCellML wrappers were really good, the amount of CellML code for the Web Lab would be minimal (call libCellML to parse the file, work with libCellML to get annotated equations).

Then Chaste code could be a separate (Python?) program that uses libCellML to read CellML, maybe do some manipulations of the equation objects for rush-larsen etc., and then write Chaste-specific C++ ?

**Comment by jonc125** [comment]
Yes, I think the WebLab-specific CellML handling would be quite different from the Chaste CellML handling if the basic CellML library is actually useful. So hopefully generic stuff would go into a community-wide Python wrapper for libcellml, or into libcellml itself, rather than just being in our code.

**Comment by jonc125** [comment]
For the experiment runner task-queue, we need a name :) I'm hoping to a large degree it can be flexible as to what it runs; for the main Web Lab it's the glue between the Django and weblab-fc components, but there could be electrochemistry & neuroscience backends, ideally without having to change more than config settings.

Ideas...

- `task-queue`
- `weblab-runner`

**Comment by MichaelClerx** [comment]
I like `weblab-runner`, as it will probably be weblab-specific!

**Comment by MichaelClerx** [comment]
How's this going?

**Comment by MichaelClerx** [comment]
@jonc125 is the missing checkbox https://github.com/ModellingWebLab/fc-runner ?
Cause if so we can close this :-)
