### ISSUE TITLE
Repeat MCMC for cell 5, check we get the same result

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#15]
See also #14 and Aidan's work

**Comment by MichaelClerx** [comment]
- [x] Get same simulation result
- [x] Get same likelihood at same position
- [x] Get same position with cmaes
- [x] Get same position with mcmc

**Comment by mirams** [comment]
Be good to see overlaid marginal histograms for each parameter under pints and compared with github data.
