### ISSUE TITLE
Establish a community agreed-upon ontology

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#21]
- [ ] Look into publishing ours somewhere
- [ ] Involve Alan Garny? Auckland?
- [ ] Have another look at Rai Winslow's massive ontology (https://radx.bioportal.bioontology.org/ontologies/EP)

**Comment by mirams** [comment]
Yeah, would be nice if (for instance) OpenCOR and Myokit could also use the membrane_voltage tag to decide the default thing to plot... As usual I suspect the best way for us to make it useful is to make sure it does everything we want to do!

I would support us moving the URL to something up to date that points to a real webpage introducing the metadata, even if it is allowed for it to be a unique nonsense URL!

**Comment by MichaelClerx** [comment]
Mine is called `membrane_potential`, but there's room for change :-)

**Comment by MichaelClerx** [comment]
Doesn't seem feasible for now. Best solution appears to be to just define and annotate ourselves, and then if there's uptake we can standardise or define a mapping from our terms to existing ones.

OK to close this @jonc125 ?

**Comment by jonc125** [comment]
Yes, though perhaps add a note about updating our ontology's URL to the relevant epic issue?
