### ISSUE TITLE
Write application/software paper describing future of web lab

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#23]
Aidan & Michael will lead, can contain stuff from unfinished 'manifesto' paper
Could include early kylie fit work
Could mention/introduce pints?
Probably a good idea to mention the need for (1) a data repo and (2) a shared ontology here

Link: https://www.journals.elsevier.com/progress-in-biophysics-and-molecular-biology/call-for-papers/call-for-papers-quantitative-systems-pharmacology-qsp (won't open in firefox because of bad https)

Deadlines:
Opens:  7-Sept-2017
Submission deadline: 15-Jan-2018
Acceptance deadline: 30-May-2018

**Comment by MichaelClerx** [comment]
Part of this issue is also to come up with a diagram like Aidan's one, describing the new web lab.

I think the current one is excellent for its purpose, but maybe emphasises the fitting aspects too much to work as a general description of the Web Lab

**Comment by jonc125** [comment]
Might be nice to think about what the fitting UI should look like as part of this (though we may not have a diagram of it in the paper; we'll see).

Also, this repo is public, so probably shouldn't put paper drafts on here! Keep them on Slack / overleaf by invite only :)

**Comment by MichaelClerx** [comment]
Another thing to work out for this is exactly how we envision future model development with the web lab

For example:

* How much happens online? Full development seems infeasible (lots of processing power needed at the moment).
* The other extreme is that people upload a problem _and_ a solution (but presumably we still want to check this solution...)
* Could/Should we set something up where people add their own machine (or a hired one, e.g. amazon, archer) as their own personal web lab back-end?
* Will we provide a "local web lab" ? And what will this look like?
  *  A VM with the full thing?
  * A VM with a limited version
  * Some managed installation / package manager thing, that installs a working web lab and all its dependencies
  * A bunch of independent Python and/or command line tools that can do all the back-end stuff (including running experiments in whatever protocol syntax we settle on)
  * Extensions to Myokit and/or OpenCOR?
  * A completely new and different thing?
* Important to remember: Local fitting makes sense, _but the web lab lets you collaborate on model development_ !

**Comment by jonc125** [comment]
"Local Web Lab" would be a VM (or Docker recipe for that, or similar) with the full thing I reckon, that they could then connect to with their normal browser.

From an earlier chat on Slack:

Michael: It should be very easy to install your own web lab. So we need to have some (programming) interface that lets you play with the web lab simulation/experiment back-end (with access to web lab (style) data). This would let people treat bits of the web lab as a kind of benchmark testing suite, without us paying for the server time (and also let people do things like massive parameter space exploration or algorithm tuning without bothering other users). Then if they get some sort of result out of this back-end (for example a new model or an updated fitting algorithm) they can port it to the public web lab

Jonathan: Easy installation of the Web Lab is certainly something I want to do, probably using something like Ansible so a single command will deploy you a virtual or real server with everything set up

Michael: I also wouldn't mind if it was just the python stuff, without a user database or a web front-end etc.!

Jonathan: Yes, each component should become pip-installable

Michael: Just had a long chat with prof. Rudy about the Web Lab (and other things). His primary concern is that it will enable people will mess around with stuff without understanding things. He suggests we should emphasise (somehow) the need to know what you're doing. Nothing we can't solve with really good annotation, documentation and openness, I think. But emphasises again how important these things will be.

**Comment by mirams** [comment]
(was submitted to PBMB, waiting to hear...)

**Comment by jonc125** [comment]
Need to return minor revisions by 60 days after 22 March 2018.

**Comment by MichaelClerx** [comment]
import datetime
    d = datetime.date(year=2018, month=3, day=22)
    d += datetime.timedelta(days=60)
    print(d)

2018-05-21

Aidan should be getting back from his holidays today!

**Comment by jonc125** [comment]
Now published at https://doi.org/10.1016/j.pbiomolbio.2018.05.011
