### ISSUE TITLE
Compare new protocol results with whole trace fitting on traditional protocols

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#27]

**Comment by mirams** [comment]
Yep - a nice extension to Kylie's sine wave work, which we never quite finished, is fitting the HH IKr model to 'traditional' data (IV curves and time constant voltage curves) and seeing how different the parameters and subsequent predictions are. 

I would like WebLab/Pints to become a place where it is easy to define what parameters are fitted to what experiments and repeat with new data.
