### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#30]
Revisit the user-stories, add a _how_ to each story (i.e. what functionality does this require? what will the UI look like? how will this be implemented?)

**Comment by jonc125** [comment]
@klapaukh can you provide advice to Michael on how to make the user stories as useful as possible for the project?

**Comment by MichaelClerx** [comment]
Done! Thanks @klapaukh Will start rewriting them soon, with some well-defined personas, being more specific, and starting with Kylie's use case as the primary one!

**Comment by MichaelClerx** [comment]
I think for now we can stick with what we have
