### ISSUE TITLE
Get the parsimonious rabbit model into CellML

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#36]
Create a CellML file for the PR model

**Comment by mirams** [comment]
The main thing is probably fitting the sodium channel model within their new rabbit model, but the whole model as well traced back to its original datasets probably makes sense too. Looking at the paper some values come from tables within older papers, so we probably want to digitise and fit the data behind all that too.

**Comment by jonc125** [comment]
Just a small job then :)

**Comment by jonc125** [comment]
The paper claims the model will appear as CellML on PMR.

**Comment by MichaelClerx** [comment]
I don't see any hint of it there (but might not be public?) If they've started on this that'd be great, if not it's not too much work to code one up in OpenCOR or Myokit and convert to CellML

**Comment by mirams** [comment]
I'll ask Pras

**Comment by MichaelClerx** [comment]
Created one and sent it to Richard, who will stick it on PMR
