### ISSUE TITLE
Add IKr protocols to WL

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#44]

**Comment by MichaelClerx** [comment]
No longer part of #69

**Comment by MichaelClerx** [comment]
Why? It's just something people could do with the WL, if they want to.

**Comment by mirams** [comment]
It's some of the validation step of Kylie use case...

**Comment by MichaelClerx** [comment]
But that no longer includes the traditional protocols, we said

**Comment by mirams** [comment]
You'll see I've put this in Stretch Goals Epic on ZenHub not the first one, it is still part of the process described in Kylie's paper that we would ideally capture/repeat.
