### ISSUE TITLE
Add IKr summary statistic plots to WL

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#45]
If we don't have them already

**Comment by MichaelClerx** [comment]
Requires https://github.com/ModellingWebLab/WebLab/issues/33

(which may not be a front-end issue?)

**Comment by MichaelClerx** [comment]
Not part of developing WL2, so closing

**Comment by mirams** [comment]
We've already got one activation curve, which is probably the easiest one to do, would be nice to add the rest at some point, making it a 'stretch goal'! Particulary nice to compare against some datasets etc.

**Comment by MichaelClerx** [comment]
But are these goals for the web lab? They seem like applications of the web lab to me. Should go in some other project, for whoever has need of these things, right?
Because we were going to look forward etc?
