### ISSUE TITLE
Find some better way of naming the python modules

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#49]
We've got `WebLab` means "front-end", and `fcX` which should probably be `wlX` I guess? No idea! But let's decide on something anyway. I'm guessing a `wl` prefix wouldn't hurt as none of these are being developed by people without web lab interests at the moment...

**Comment by MichaelClerx** [comment]
If we follow a scheme like `project_component`, then `project` is the bit that competes with existing python libraries. So it'd make sense to have a full `weblab_` there instead of `wl_` I think.
Given that we already have a `weblab-fc` repo, and since there probably won't be more than ~10 core web lab projects, maybe we could stick with `weblab_xx` where `xx` is an abbreviation, preferably two letters, that indicates the component?

For example

- CellML manipulation `weblab_cm`
- Code generation `weblab_cg`
- Functional curation script reading / handling `weblab_fc`

Something like that? @jonc125 @tamuri ?

**Comment by jonc125** [comment]
Seems reasonable to me. The original reason for choosing the more general `cellmlmanip` was that we hoped things outside Web Lab would use it eventually...

**Comment by MichaelClerx** [comment]
Closing due to lack of interest? @jonc125 ?
