### ISSUE TITLE
Weak provenance description

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#50]
The web lab should be able to do this:

![web-of-models-and-data](https://user-images.githubusercontent.com/517644/49220444-20913580-f3ce-11e8-8bf3-f53fe836dbb7.png)

**Comment by MichaelClerx** [comment]
Will probably have to leave this for WL3. No current plans to create an ontology or a UI for this. "Looking forward" has priority.
Closing this, if that's ok @mirams @jonc125

**Comment by jonc125** [comment]
It might be worth creating a "Web Lab 3" issue where you can store links to this kind of thing, so it's easier to find for future reference?

**Comment by MichaelClerx** [comment]
Thanks! I've got a few text files with most of this spelled out, that I'm still working on occasionally in case we want to do a WL3 grant. So might be better not to stick them online for now?

**Comment by mirams** [comment]
Yeah, fine to skip this. I'm primarily interested in tracking data to model for our cases where it's completely defined
