### ISSUE TITLE
Testing model generation

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/project_issues#53]
Hi @jonc125 !

I'd like to run a simulation with an fccodegen generated model, but not sure about the best way to set it up.

One idea I had was to create a repo that uses [`fccodegen`](https://github.com/ModellingWebLab/fccodegen) and [`weblab-fc`](https://github.com/ModellingWebLab/weblab-fc) and then generates and runs a model (this would require only the bits of `weblab-fc` that the generated model inherits, I think? An issue here would be that I don't see a setup.py for weblab-fc. If this works, this test repo can grow into an 'offline command-line weblab' component. #51 

Alternatively we could write it as part of weblab-fc's tests. But to be honest I don't understand the layout of that project very well!

**Comment by jonc125** [comment]
Initially at least I think this should be done through a test in weblab-fc – there’s an issue in that repo about it. I’m working on restructuring the repo as a standard Python package to support this in the packaging branch.

**Comment by MichaelClerx** [comment]
This is now handled in weblab_cg + cellmlmanip, with relevant tickets there
