### ISSUE TITLE
Announce retirement of WL1

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#56]
Once we've done the workshop, we should tell existing users that WL1 will be retired in a few months and they should create accounts on WL2 instead.

At that point we'll need to be more careful about re-deploying scrambler, and set up a staging server for testing things out.

Also need to inform Fergus when we have migrated the 'live' WL instance to WL2 on scrambler so he can upgrade travis.

**Comment by mirams** [comment]
Actually done :-)
