### ISSUE TITLE
Epic 1: WebLab code gen with cellmlmanip

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#57]
- Add the model manipulation features needed for all Web Lab protocol features
- Be able to run all existing protocols
- Should also support [Chaste code generation](https://github.com/modellingweblab/weblab-cg/issues/3), fully replacing pycml, which will be @MauriceHendrix's priority.

Key tasks to get there:
- ModellingWebLab/weblab-fc#23 gives an ordered list of protocols to get working, adding features incrementally.
    - ModellingWebLab/weblab-fc#22 is the first of these
    - Followed by ModellingWebLab/weblab-fc#30
- ModellingWebLab/cellmlmanip#21 discusses the medium-level model manipulation features that we need to implement these.
- Could @tamuri review open issues on cellmlmanip and close those that have been completed?

In terms of separation of concerns,
- Parsing of Web Lab protocols goes in https://github.com/ModellingWebLab/weblab-fc, using the model interface section of these to control the code generation process. It uses the following.
- Model manipulation is all done by https://github.com/ModellingWebLab/cellmlmanip, encapsulating the Sympy equations and related metadata, and providing methods to do common manipulations e.g. replacing equations, tracking dependencies, topological sorting.
- Basic code generation functionality goes in https://github.com/ModellingWebLab/weblab-cg, including templates. Pretty much this library should probably just be given the 'model' object from cellmlmanip and the template to use. Depending on the template (particularly for Chaste code gen) different methods on cellmlmanip may need to be called to get info, e.g. Jacobian matrices for Chaste CVODE solvers.

Background/reference reading:
- [functional curation paper](https://doi.org/10.1016/j.pbiomolbio.2011.06.003)
- Chaste code generation [for tissue simuations](https://doi.org/10.1016/j.pbiomolbio.2011.06.002) and [for single cell](https://doi.org/10.3389/fphys.2014.00511)
- [Web Lab protocol language documentation](https://chaste.cs.ox.ac.uk/trac/wiki/FunctionalCuration/ProtocolSyntax#Modelinterface)
- You can also look at any of the 'moderated' protocols on the Web Lab, which are generally well-commented to explain what they're doing

See also #12 for some background.

**Comment by MichaelClerx** [comment]
@jonc125 do we count these two as part of this issue?

- [ ] https://github.com/ModellingWebLab/weblab-fc/issues/181
- [ ] https://github.com/ModellingWebLab/weblab-fc/issues/24 

Apart from that, this epic is done?

**Comment by MauriceHendrix** [comment]
I wouldn't call https://github.com/ModellingWebLab/chaste-codegen/issues/3 done yet

**Comment by MichaelClerx** [comment]
That's not a web lab goal though, we've split that off

**Comment by MichaelClerx** [comment]
> @jonc125 do we count these two as part of this issue?
> 
>     * [ ]  [ModellingWebLab/weblab-fc#181](https://github.com/ModellingWebLab/weblab-fc/issues/181)
> 
>     * [ ]  [ModellingWebLab/weblab-fc#24](https://github.com/ModellingWebLab/weblab-fc/issues/24)
> 
> 
> Apart from that, this epic is done?

Actually, I see ModellingWebLab/weblab-fc#24 is listed as part of epic 3 instead? Should I add ModellingWebLab/weblab-fc#24 and ModellingWebLab/weblab-fc#59 there and close this epic?
