### ISSUE TITLE
Use case 2: Pras & Rick

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#70]
Fitting a 'whole' action potential model, using the Gray-Pathmanathan parsimonious rabbit model. See series of emails with data and details 10-15th May 2019.

If we get ambitious then a newer version with full UQ is underway at present (basically for WL this would mean some form of MCMC rather than optimisation), but I think we should stick to the basic version.

**Comment by MichaelClerx** [comment]
@gary @jonc125 I think we agreed we'd just do IKr fitting - with several models, so Kylie/Chon/Sanmitra models and protocols, but no combining of results with means of hierarchical procedures or anything.
Think that means we can close #70 and #71 ?

**Comment by mirams** [comment]
Certainly can be mothballed - maybe we can create a github label for that so we can identify mothballed rather than finished tasks (and bring them back easily later on) even if we close to rationalise the Issue tracker?

**Comment by MichaelClerx** [comment]
There's an "icebox" thing in this Zenhub thing. Could use that?

**Comment by MichaelClerx** [comment]
I've just done some labels as well then :D

**Comment by jonc125** [comment]
The icebox in ZenHub keeps the issue open. So if you want to close it a label is better.
