### ISSUE TITLE
Harmony 2020

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#75]
Notes & links to topics for discussion / development at Harmony 2020.

* OMEX metadata specification (cf #63 #64)
    * Metadata for CSV files https://github.com/MichaelClerx/ephys-data-repo/issues/2 #63
    * Simpler linking of CSV file columns & linked protocol outputs - [Gary had a good idea for this](https://github.com/ModellingWebLab/project_issues/issues/74#issuecomment-566734800)
    * https://github.com/ModellingWebLab/WebLab/issues/96
* Linking to Physiome Model Repository #8 
    * Latest status on this: https://github.com/ModellingWebLab/WebLab/issues/254
* Would this kind of parameter fitting re-run approach be useful for other COMBINE standards / domains? (i.e. could others make use of the WL2 front-end?)

**Comment by skeating** [comment]
Questions:
1. Do we have any issue with the OMEX metadata specification (expected to be ratified/accepted at HARMONY ? https://drive.google.com/file/d/1AngoIjQovM7DpCwR0W6TP0admMloGa9k/view
You say simpler linking - does this mean you want the spec simplified although the section on CSV doesnt really have much

2. Linking to PMR seems a long outstanding thing on grant. Who needs talking to about this, what needs to happen etc.

3. I assume with point three (is WL2 front end useful) we need to talk to other people who do parameter fitting ?

**Comment by MichaelClerx** [comment]
And do we want to look at frictionlessdata like matthias Koenig suggested?

**Comment by MichaelClerx** [comment]
PMR was very much in a state of flux last time, I recall?
But @helenst worked something out with Auckland's Tommy Yu?

**Comment by MichaelClerx** [comment]
@metatoaster ?

**Comment by metatoaster** [comment]
Hi all, the [documentation on the Webservice for PMR](https://aucklandphysiomerepository.readthedocs.io/en/latest/webservice.html) is part of the documentation link that may be found on the top level menu at the repository, and there contained some of the most common use cases for this feature.  There hasn't been significant changes to what this feature offered since its introduction.

**Comment by jonc125** [comment]
Responding to @skeating :

>     1. Do we have any issue with the OMEX metadata specification (expected to be ratified/accepted at HARMONY ? https://drive.google.com/file/d/1AngoIjQovM7DpCwR0W6TP0admMloGa9k/view
>        You say simpler linking - does this mean you want the spec simplified although the section on CSV doesnt really have much

I voted to ratify the spec. The 'simpler linking' thing was a suggestion by Gary; now linked.

>     2. Linking to PMR seems a long outstanding thing on grant. Who needs talking to about this, what needs to happen etc.

I've created a new issue in the WebLab repo with the latest state on this.

>     3. I assume with point three (is WL2 front end useful) we need to talk to other people who do parameter fitting ?

Yep!

**Comment by jonc125** [comment]
> And do we want to look at frictionlessdata like matthias Koenig suggested?

Definitely worth seeing what other attendees think of it. Not sure how far we'd get implementing something during the project, but if COMBINE archives start adding this kind of metadata structure it'd be worth getting on board. And might be pretty easy to do given it's supposed to be lightweight!

**Comment by MichaelClerx** [comment]
We're at the same point as 2 years ago regarding annotated data files.

Everybody wants a CSV based standard, nobody wants to create one (the problem being that everyone here has experience in setting up standards).

Discussed CSV-on-the-web, our hierarchical idea, frictionless data, using excel

Germans prefer TSV to avoid problems with commas functioning as the decimal system (which windows does system-wide in many applications)

Brett Oliver made a good point saying it started from who you were sharing with: if it's you, don't care; if it's some local, care a little; if it's external parties, care a lot.
One problem we have is that we don't really know who we want to share with

Current consensus seems to just do what you feel like and hopefull something will emerge :-| 

See also: https://twitter.com/andreshouse/status/1238037255438110723
